// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_packet.proto

#include "log_packet.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class log_packetDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<log_packet>
      _instance;
} _log_packet_default_instance_;
namespace protobuf_log_5fpacket_2eproto {
void InitDefaultslog_packetImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_log_packet_default_instance_;
    new (ptr) ::log_packet();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::log_packet::InitAsDefaultInstance();
}

void InitDefaultslog_packet() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultslog_packetImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::log_packet, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::log_packet, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::log_packet, log_len_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::log_packet, packet_rec_ip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::log_packet, log_level_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::log_packet, send_user_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::log_packet, log_msg_),
  4,
  0,
  1,
  2,
  3,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::log_packet)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_log_packet_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "log_packet.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020log_packet.proto\"p\n\nlog_packet\022\017\n\007log_"
      "len\030\001 \002(\006\022\025\n\rpacket_rec_ip\030\002 \002(\t\022\021\n\tlog_"
      "level\030\003 \002(\t\022\026\n\016send_user_name\030\004 \002(\014\022\017\n\007l"
      "og_msg\030\005 \002(\014"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 132);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "log_packet.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_log_5fpacket_2eproto

// ===================================================================

void log_packet::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int log_packet::kLogLenFieldNumber;
const int log_packet::kPacketRecIpFieldNumber;
const int log_packet::kLogLevelFieldNumber;
const int log_packet::kSendUserNameFieldNumber;
const int log_packet::kLogMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

log_packet::log_packet()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_log_5fpacket_2eproto::InitDefaultslog_packet();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:log_packet)
}
log_packet::log_packet(const log_packet& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  packet_rec_ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_packet_rec_ip()) {
    packet_rec_ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.packet_rec_ip_);
  }
  log_level_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_log_level()) {
    log_level_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.log_level_);
  }
  send_user_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_send_user_name()) {
    send_user_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.send_user_name_);
  }
  log_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_log_msg()) {
    log_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.log_msg_);
  }
  log_len_ = from.log_len_;
  // @@protoc_insertion_point(copy_constructor:log_packet)
}

void log_packet::SharedCtor() {
  _cached_size_ = 0;
  packet_rec_ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  log_level_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  send_user_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  log_msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  log_len_ = GOOGLE_ULONGLONG(0);
}

log_packet::~log_packet() {
  // @@protoc_insertion_point(destructor:log_packet)
  SharedDtor();
}

void log_packet::SharedDtor() {
  packet_rec_ip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  log_level_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  send_user_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  log_msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void log_packet::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* log_packet::descriptor() {
  ::protobuf_log_5fpacket_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_log_5fpacket_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const log_packet& log_packet::default_instance() {
  ::protobuf_log_5fpacket_2eproto::InitDefaultslog_packet();
  return *internal_default_instance();
}

log_packet* log_packet::New(::google::protobuf::Arena* arena) const {
  log_packet* n = new log_packet;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void log_packet::Clear() {
// @@protoc_insertion_point(message_clear_start:log_packet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!packet_rec_ip_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*packet_rec_ip_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!log_level_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*log_level_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(!send_user_name_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*send_user_name_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(!log_msg_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*log_msg_.UnsafeRawStringPointer())->clear();
    }
  }
  log_len_ = GOOGLE_ULONGLONG(0);
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool log_packet::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:log_packet)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required fixed64 log_len = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_log_len();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_FIXED64>(
                 input, &log_len_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string packet_rec_ip = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_packet_rec_ip()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->packet_rec_ip().data(), static_cast<int>(this->packet_rec_ip().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "log_packet.packet_rec_ip");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required string log_level = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_log_level()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->log_level().data(), static_cast<int>(this->log_level().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "log_packet.log_level");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bytes send_user_name = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_send_user_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required bytes log_msg = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_log_msg()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:log_packet)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:log_packet)
  return false;
#undef DO_
}

void log_packet::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:log_packet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required fixed64 log_len = 1;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteFixed64(1, this->log_len(), output);
  }

  // required string packet_rec_ip = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->packet_rec_ip().data(), static_cast<int>(this->packet_rec_ip().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "log_packet.packet_rec_ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->packet_rec_ip(), output);
  }

  // required string log_level = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->log_level().data(), static_cast<int>(this->log_level().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "log_packet.log_level");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->log_level(), output);
  }

  // required bytes send_user_name = 4;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->send_user_name(), output);
  }

  // required bytes log_msg = 5;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->log_msg(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:log_packet)
}

::google::protobuf::uint8* log_packet::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:log_packet)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required fixed64 log_len = 1;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFixed64ToArray(1, this->log_len(), target);
  }

  // required string packet_rec_ip = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->packet_rec_ip().data(), static_cast<int>(this->packet_rec_ip().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "log_packet.packet_rec_ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->packet_rec_ip(), target);
  }

  // required string log_level = 3;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->log_level().data(), static_cast<int>(this->log_level().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "log_packet.log_level");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->log_level(), target);
  }

  // required bytes send_user_name = 4;
  if (cached_has_bits & 0x00000004u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->send_user_name(), target);
  }

  // required bytes log_msg = 5;
  if (cached_has_bits & 0x00000008u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->log_msg(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:log_packet)
  return target;
}

size_t log_packet::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:log_packet)
  size_t total_size = 0;

  if (has_packet_rec_ip()) {
    // required string packet_rec_ip = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->packet_rec_ip());
  }

  if (has_log_level()) {
    // required string log_level = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->log_level());
  }

  if (has_send_user_name()) {
    // required bytes send_user_name = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->send_user_name());
  }

  if (has_log_msg()) {
    // required bytes log_msg = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->log_msg());
  }

  if (has_log_len()) {
    // required fixed64 log_len = 1;
    total_size += 1 + 8;
  }

  return total_size;
}
size_t log_packet::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:log_packet)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x0000001f) ^ 0x0000001f) == 0) {  // All required fields are present.
    // required string packet_rec_ip = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->packet_rec_ip());

    // required string log_level = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->log_level());

    // required bytes send_user_name = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->send_user_name());

    // required bytes log_msg = 5;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->log_msg());

    // required fixed64 log_len = 1;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void log_packet::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:log_packet)
  GOOGLE_DCHECK_NE(&from, this);
  const log_packet* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const log_packet>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:log_packet)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:log_packet)
    MergeFrom(*source);
  }
}

void log_packet::MergeFrom(const log_packet& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:log_packet)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_packet_rec_ip();
      packet_rec_ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.packet_rec_ip_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_log_level();
      log_level_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.log_level_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_send_user_name();
      send_user_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.send_user_name_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_log_msg();
      log_msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.log_msg_);
    }
    if (cached_has_bits & 0x00000010u) {
      log_len_ = from.log_len_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void log_packet::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:log_packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void log_packet::CopyFrom(const log_packet& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:log_packet)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool log_packet::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;
  return true;
}

void log_packet::Swap(log_packet* other) {
  if (other == this) return;
  InternalSwap(other);
}
void log_packet::InternalSwap(log_packet* other) {
  using std::swap;
  packet_rec_ip_.Swap(&other->packet_rec_ip_);
  log_level_.Swap(&other->log_level_);
  send_user_name_.Swap(&other->send_user_name_);
  log_msg_.Swap(&other->log_msg_);
  swap(log_len_, other->log_len_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata log_packet::GetMetadata() const {
  protobuf_log_5fpacket_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_log_5fpacket_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
